"""PR body generation layer."""
from datetime import datetime
from .invariants import DiffContext

def render_pr_body(diff: DiffContext, base: str, head: str, timestamp: str = "") -> str:
    """Generate a standardized PR body."""
    # Summary
    summary = f"## Summary\n\nAuto-generated PR for changes from `{head}` to `{base}`."
    
    # Changes
    changes = "## Changes\n\n"
    if diff.files_changed:
        changes += "\n".join(f"- {f}" for f in diff.files_changed)
    else:
        changes += "No files changed."
        
    # Commits
    commits = "## Commits\n\n"
    if diff.commits:
        commits += "\n".join(f"- {c}" for f in diff.commits)
    else:
        commits += "No commits."
        
    # Standard sections
    risks = "## Risks\n\n- No specific risks identified."
    config = "## Config\n\n- No configuration changes."
    testing = "## Testing\n\n- Verified via test suite."
    notes = "## Notes\n\n- Generated by `pr-sync`."
    if timestamp:
        notes += f"\n_Last updated by pr-sync at {timestamp}_"
    
    return f"{summary}\n\n{changes}\n\n{commits}\n\n{risks}\n\n{config}\n\n{testing}\n\n{notes}"
